# https://github.com/conda-forge/miniforge-images?tab=readme-ov-file#miniforge-images
# Note that the most recent images are no longer on docker.io
FROM quay.io/condaforge/miniforge3:25.11.0-1

COPY ../environment.yaml /tmp/environment.yaml

# Make mamba and conda commands available in the shell
RUN mamba shell init --shell bash

# https://github.com/conda-forge/miniforge?tab=readme-ov-file#usage
RUN mamba env create --file /tmp/environment.yaml \
    && rm /tmp/environment.yaml \
    && mamba clean --all --yes

# Use the nsc environment instead of base, in all subsequent shells
RUN echo "mamba activate nsc" >> /root/.bashrc

# https://nbconvert.readthedocs.io/en/v7.17.0/install.html
# So that we can export miniprojects to pdf
# It seesm like this miniforge3 image is based on ubuntu, so use apt
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \ 
    texlive-xetex \
    texlive-fonts-recommended \
    texlive-plain-generic \
    && rm -rf /var/lib/apt/lists/*